const marvelCards = [
  {name:'atmanAvispa', characterImage: 'memo-marvel/atmanAvispa.png', posterImage: 'memo-marvel/marvel.png'},
  {name:'capitan', characterImage: 'memo-marvel/capitan.png', posterImage: 'memo-marvel/marvel.png'},
  {name:'daredevil', characterImage: 'memo-marvel/daredevil.png', posterImage: 'memo-marvel/marvel.png'},
  {name:'capitana', characterImage: 'memo-marvel/capitana.png', posterImage: 'memo-marvel/marvel.png'},
  {name:'deadpoll', characterImage: 'memo-marvel/deadpoll.png', posterImage: 'memo-marvel/marvel.png'},
  {name:'fantasticos', characterImage: 'memo-marvel/fantasticos.png', posterImage: 'memo-marvel/marvel.png'},
  {name:'guardianes', characterImage: 'memo-marvel/guardianes.png', posterImage: 'memo-marvel/marvel.png'},
  {name:'hulk', characterImage: 'memo-marvel/hulk.png', posterImage: 'memo-marvel/marvel.png'},
  {name:'panter', characterImage: 'memo-marvel/panter.png', posterImage: 'memo-marvel/marvel.png'},
  {name:'iron', characterImage: 'memo-marvel/iron.png', posterImage: 'memo-marvel/marvel.png'},
  {name:'spiderman', characterImage: 'memo-marvel/spiderman.png', posterImage: 'memo-marvel/marvel.png'},
  {name:'strange', characterImage: 'memo-marvel/strange.png', posterImage: 'memo-marvel/marvel.png'},
]
const dcCards = [
  {name:'aquaman', characterImage: 'memo-dc/aquaman.png', posterImage: 'memo-dc/dc1.png'},
  {name:'batman', characterImage: 'memo-dc/batman.png', posterImage: 'memo-dc/dc1.png'},
  {name:'black', characterImage: 'memo-dc/black.png', posterImage: 'memo-dc/dc1.png'},
  {name:'flash', characterImage: 'memo-dc/flash.png', posterImage: 'memo-dc/dc1.png'},
  {name:'green', characterImage: 'memo-dc/green.png', posterImage: 'memo-dc/dc1.png'},
  {name:'joker', characterImage: 'memo-dc/joker.png', posterImage: 'memo-dc/dc1.png'},
  {name:'blue', characterImage: 'memo-dc/blue.png', posterImage: 'memo-dc/dc1.png'},
  {name:'harley', characterImage: 'memo-dc/harley.png', posterImage: 'memo-dc/dc1.png'},
  {name:'shazam', characterImage: 'memo-dc/shazam.png', posterImage: 'memo-dc/dc1.png'},
  {name:'catwoman', characterImage: 'memo-dc/catwoman.png', posterImage: 'memo-dc/dc1.png'},
  {name:'superman', characterImage: 'memo-dc/superman.png', posterImage: 'memo-dc/dc1.png'},
  {name:'wonder', characterImage: 'memo-dc/wonder.png', posterImage: 'memo-dc/dc1.png'},
  
]
const disneyCards = [
  {name:'aladin', characterImage: 'disney/aladin.png', posterImage: 'disney/disney.png'},
  {name:'ariel', characterImage: 'disney/ariel.png', posterImage: 'disney/disney.png'},
  {name:'bellabestia', characterImage: 'disney/bellabestia.png', posterImage: 'disney/disney.png'},
  {name:'blancanieves', characterImage: 'disney/blancanieves.png', posterImage: 'disney/disney.png'},
  {name:'brave', characterImage: 'disney/brave.png', posterImage: 'disney/disney.png'},
  {name:'elsa', characterImage: 'disney/elsa.png', posterImage: 'disney/disney.png'},
  {name:'mickey', characterImage: 'disney/mickey.png', posterImage: 'disney/disney.png'},
  {name:'panda', characterImage: 'disney/panda.png', posterImage: 'disney/disney.png'},
  {name:'peter', characterImage: 'disney/peter.png', posterImage: 'disney/disney.png'},
  {name:'pinocho', characterImage: 'disney/pinocho.png', posterImage: 'disney/disney.png'},
  {name:'planetaTesoro', characterImage: 'disney/planetaTesoro.png', posterImage: 'disney/disney.png'},
  {name:'reyleon', characterImage: 'disney/reyleon.png', posterImage: 'disney/disney.png'},
]
const familyCards = [
  {name:'albi', characterImage: 'family/albi.png', posterImage: 'family/logo.png'},
  {name:'david', characterImage: 'family/david.png', posterImage: 'family/logo.png'},
  {name:'elia', characterImage: 'family/elia.png', posterImage: 'family/logo.png'},
  {name:'gerard', characterImage: 'family/gerard.png', posterImage: 'family/logo.png'},
  {name:'hijos', characterImage: 'family/hijos.png', posterImage: 'family/logo.png'},
  {name:'joan', characterImage: 'family/joan.png', posterImage: 'family/logo.png'},
  {name:'montse', characterImage: 'family/montse.png', posterImage: 'family/logo.png'},
  {name:'nietas', characterImage: 'family/nietas.png', posterImage: 'family/logo.png'},
  {name:'alba', characterImage: 'family/alba.png', posterImage: 'family/logo.png'},
  {name:'noa', characterImage: 'family/noa.png', posterImage: 'family/logo.png'},
  {name:'papa', characterImage: 'family/papa.png', posterImage: 'family/logo.png'},
  {name:'sergio', characterImage: 'family/sergio.png', posterImage: 'family/logo.png'},
]
const señorAnillosCards = [
  {name:'arwen', characterImage: 'señorAnillos/arwen.png', posterImage: 'señorAnillos/anillo.png'},
  {name:'elrond', characterImage: 'señorAnillos/elrond.png', posterImage: 'señorAnillos/anillo.png'},
  {name:'frodo', characterImage: 'señorAnillos/frodo.png', posterImage: 'señorAnillos/anillo.png'},
  {name:'aragon', characterImage:'señorAnillos/aragon.png', posterImage: 'señorAnillos/anillo.png'},
  {name:'gandalf', characterImage:'señorAnillos/gandalf.png', posterImage: 'señorAnillos/anillo.png'},
  {name:'gollum', characterImage: 'señorAnillos/gollum.png', posterImage: 'señorAnillos/anillo.png'},
  {name:'grimbli.png', characterImage: 'señorAnillos/grimbli.png', posterImage: 'señorAnillos/anillo.png'},
  {name:'legolas', characterImage: 'señorAnillos/legolas.png', posterImage: 'señorAnillos/anillo.png'},
  {name:'merrypipi', characterImage: 'señorAnillos/merrypipi.png', posterImage: 'señorAnillos/anillo.png'},
  {name:'saruman', characterImage: 'señorAnillos/saruman.png', posterImage: 'señorAnillos/anillo.png'},
  {name:'urukhai', characterImage: 'señorAnillos/urukhai.png', posterImage: 'señorAnillos/anillo.png'},
  {name:'samsagaz', characterImage: 'señorAnillos/samsagaz.png', posterImage: 'señorAnillos/anillo.png'}, 
]
const harryPotterCards = [
  {name:'albus', characterImage: 'harryPotter/albus.png', posterImage: 'harryPotter/logo.png'},
  {name:'dobby', characterImage: 'harryPotter/dobby.png', posterImage: 'harryPotter/logo.png'},
  {name:'draco', characterImage: 'harryPotter/draco.png', posterImage: 'harryPotter/logo.png'},
  {name:'hadrid', characterImage: 'harryPotter/hadrid.png', posterImage: 'harryPotter/logo.png'},
  {name:'hermion', characterImage: 'harryPotter/hermion.png', posterImage: 'harryPotter/logo.png'},
  {name:'luna', characterImage: 'harryPotter/luna.png', posterImage: 'harryPotter/logo.png'},
  {name:'minerva', characterImage: 'harryPotter/minerva.png', posterImage: 'harryPotter/logo.png'},
  {name:'moody', characterImage: 'harryPotter/moody.png', posterImage: 'harryPotter/logo.png'},
  {name:'remus', characterImage: 'harryPotter/remus.png', posterImage: 'harryPotter/logo.png'},
  {name:'ron', characterImage: 'harryPotter/ron.png', posterImage: 'harryPotter/logo.png'},
  {name:'severus', characterImage: 'harryPotter/severus.png', posterImage: 'harryPotter/logo.png'},
  {name:'harry', characterImage: 'harryPotter/harry.png', posterImage: 'harryPotter/logo.png'},
]
const starwarsCards = [
  {name:'anakyn', characterImage: 'starwars/anakyn.png', posterImage: 'starwars/logo.png'},
  {name:'bb8', characterImage: 'starwars/bb8.png', posterImage: 'starwars/logo.png'},
  {name:'bobafelt', characterImage: 'starwars/bobafelt.png', posterImage: 'starwars/logo.png'},
  {name:'c3po', characterImage: 'starwars/c3po.png', posterImage: 'starwars/logo.png'},
  {name:'chewbaca', characterImage: 'starwars/chewbaca.png', posterImage: 'starwars/logo.png'},
  {name:'darkVader', characterImage: 'starwars/darkVader.png', posterImage: 'starwars/logo.png'},
  {name:'darthMaul', characterImage: 'starwars/darthMaul.png', posterImage: 'starwars/logo.png'},
  {name:'hansolo', characterImage: 'starwars/hansolo.png', posterImage: 'starwars/logo.png'},
  {name:'leia', characterImage: 'starwars/leia.png', posterImage: 'starwars/logo.png'},
  {name:'luke', characterImage: 'starwars/luke.png', posterImage: 'starwars/logo.png'},
  {name:'r2d2', characterImage: 'starwars/r2d2.png', posterImage: 'starwars/logo.png'},
  {name:'yoda', characterImage: 'starwars/yoda.png', posterImage: 'starwars/logo.png'},
]